### ISSUE TITLE
Better Branding

### ISSUE THREAD

**Issue by GreenCappuccino** [CentralTimes/centraltimes_app#36]
Current splash configuration shows color inconsistency between icon and background.
![image](https://user-images.githubusercontent.com/28021387/137411547-71a94a6e-5324-4d4e-9af8-4c10f6d8f9b9.png)
App icon also displays poorly on various Android platforms (Always square).
![image](https://user-images.githubusercontent.com/28021387/137411672-3b189d98-4882-4fed-ba1e-5122a171a367.png)

 - [x] Make App Icon Transparent
 - [x] Generate backgrounds and icon variants using Android Studio
 - [x] Do so on iOS somehow
 - [x] Ensure swatches match Central Times branding guide

**Comment by manamster** [comment]
Fixed the swatches according to what Cameron wanted. Also replaced deprecated primaryColor in ThemeData with ColorScheme.
