### ISSUE TITLE
Resaving post pushes post to bottom

### ISSUE THREAD

**Issue by dwu359** [CentralTimes/centraltimes_app#51]
**Describe the bug**
If you remove and resave a post by disabling and then enabling the bookmark icon of a post in the saved page, the post is pushed to the bottom of the list of posts rather than remaining in its original location.

**How to Resolve**
In the saved page, remove and add a post by index rather than by the post's Wordpress id.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.1

**Smartphone (please complete the following information):**
 - Device: iPhone13 Simulator
 - OS: iOS 15.2

**Comment by manamster** [comment]
Its been done for a while IDK why it was left open. It is in canary and stuff should be done with this.
