### ISSUE TITLE
Create a wiki for references

### ISSUE THREAD

**Issue by dwu359** [CentralTimes/centraltimes_app#53]

**Comment by manamster** [comment]
Created a basic home page and FAQ page. Ill work on filling out the FAQ page a little bit in my free time.

**Comment by dwu359** [comment]
Brian will look into wiki.js as a possible form of a wiki

**Comment by manamster** [comment]
@GreenCappuccino Did you ever look at wiki.js as a solution? If not then I might just continue adding stuff to the github wiki and close this issue.

**Comment by GreenCappuccino** [comment]
yean no i didnt. please close then
